### ISSUE TITLE
vcs json output order

### ISSUE THREAD

**Issue by malankriel** [AutoActuary/deploy-scripts#36]
The order of the json outputs should ideally be the same as the order it occurs in the VCS table:
![image](https://user-images.githubusercontent.com/51300197/96229393-20d15480-0f97-11eb-88b1-489290129d67.png)

This is not a high priority, but if it's a one-liner / additional argument I think we should go for it

Some pros:
 - more readable when comparing code
 - avoid unexpected change in order if the case of a header changes. E.g. if Formula changes to formula it will move in all the instances
 - could be replicated with a vba export (thinking of potential clients that doesn't allow .exe's to be shipped like we see in New Zealand

Some cons:
 - If we change the order of columns, it will come through as changes in the json file

**Comment by rudolfbyker** [comment]
It could be a one-liner fix, but I don't think it should. We have had the argument about ordered dicts in Python 3.7+ before, and Simon convinced me at the time, but after reading this http://gandenberger.org/2018/03/10/ordered-dicts-vs-ordereddict/ I really think we should use an OrderedDict whenever we want to explicitly keep the ordering, rather than relying on a CPython implementation detail.
